config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

   root to: "home#index"

   resources :user do
    resources :category do
    resources :transaction
    end
   end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

    belongs_to :user ,  foreign_key: 'user_id' , class_name: 'User'

    has_many :transaction_categories , dependent: :delete_all
    has_many :transaction_entities , through:  :transaction_categories

    validates :name  , presence: true, length: { maximum: 30 }
    validates  :icon , presence: true
end

app/models/transaction_category.rb
class TransactionCategory < ApplicationRecord
    belongs_to :transaction_entity , foreign_key: 'transaction_entities_id'
    belongs_to :category , foreign_key: 'category_id'
end

app/models/transaction_entity.rb
class TransactionEntity < ApplicationRecord
    belongs_to :user , foreign_key: 'user_id' , class_name: 'User'

    has_many :transaction_categories , dependent: :delete_all
    has_many :categories , through: :transaction_categories

    validates :name, presence: true, length: { maximum: 30 }
    validates :amount, presence: true, numericality: { greater_than: 0 }
   
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :transactions , foreign_key: 'user_id'
  has_many :categories , foreign_key: 'user_id'

  validates :name , :email , :password , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    end

    
    private 
    def after_sign_in_path_for(resource)
      user_category_index_path(current_user.id)
    end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

    def index
        @category=Category.all

    end

    def new
        @category = Category.new
    end

    def show
        @category= Category.find(params[:id])
        @transaction_categories=@category.transaction_categories
        @transaction_entity= @category.transaction_entities.order('created_at DESC')
        @total_amount =  @category.transaction_entities.sum(:amount)
    end

    def create
        @category = Category.new(category_params)
        @category.user_id = params[:user_id]
        respond_to do |format|
            format.html do
                if @category.save
                redirect_to user_category_index_path(current_user.id) , notice: 'Category Add Successfuly'
                else
                    flash[:error] = @category.errors.full_messages
                    redirect_to new_user_category_path(current_user.id), status: :unprocessable_entity
                end
               end
            end
    end

    def category_params
        params.require(:category).permit(:name , :icon)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, except: :index

    def index
    end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController

    def index
        
    end

   def new
    @transaction_entity=TransactionEntity.new
    @category = Category.all
   end

    def create
        @transaction = TransactionEntity.new(name:transaction_params[:name] , amount: transaction_params[:amount] )
        @transaction.user_id = current_user.id

        respond_to do |format|
            format.html do
              if transaction_params[:category_ids].present?
                if @transaction.save
                    transaction_params[:category_ids].each do |category_id|
                        TransactionCategory.create( category_id: category_id, transaction_entities_id: @transaction.id)
                    end
                    redirect_to user_category_path(current_user.id , params[:category_id]) , notice: 'Transaction Add Successfuly'
                else
                    flash[:error] = @transaction.errors.full_messages
                     redirect_to new_user_category_transaction_path(current_user.id , params[:category_id]), status: :unprocessable_entity
                end
                
              else
                
                error_array = @transaction.errors.full_messages
                error_array << 'Please select at least one category'
                flash[:error] = error_array
                redirect_to request.referrer, status: :unprocessable_entity
              end
            end
        end
    end

    def transaction_params
        params.require(:transaction_entity).permit(:name , :amount , category_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/category/index.html.erb
<%= stylesheet_link_tag "category"%> 
<nav class='navbar'>
  <i class="fa fa-bars"></i>
  <p><b>CATEGORY</b></p>
  <a href="<%=  destroy_user_session_path%>"><i class="fa fa-sign-out"></i></a>
</nav>
<% if notice%>
<div id='alert-box'>
<%= notice%><i class="fa fa-check"></i>
</div>
<%end%>
<section class='transaction-list'>
<% @category.each do |item| %>
 
    <a href="<%= user_category_path(current_user.id , item.id) %>">
    <div class='card'>
        <%= image_tag "#{item.icon}" %>
        <div id='info-part'>
            <h1><%= item.name%></h1>
            <p><i class='fa fa-calendar'></i> <%= item.created_at.strftime('%B %d %Y')%></p>
        </div>
        <h4><i class='fa fa-money'></i> <%= item.transaction_entities.sum(:amount)%>$</h4>
    </div>
    </a>
<% end %>
</section>
<div id='footer-btn'>
    <div id='btn'>
        <h3><%= link_to 'ADD NEW CATEGORY' , new_user_category_path%></h3>
    </div>
</div>

app/views/category/new.html.erb
<%= stylesheet_link_tag "category"%> 
<nav class='navbar'>
  <a href="<%= user_category_index_path(current_user.id)%>" > <i class="fa fa-arrow-left"></i></a>
  <p><b>NEW CATEGORY</b></p>
  <i class="fa fa-searc"></i>
</nav>


<section class='category-form'>
<%= form_with model: @category , url: user_category_index_path , method: :post , local: true, class: "form-control" do |f|  %>
    <div class="form-field">
    <%= f.text_field :name , autofocus:  true , autocomplete: "name" , placeholder: 'Enter Category Name'%>
    </div>
    <div class="form-field">
       <%= f.url_field :icon , autocomplete: "name" , placeholder: 'Enter icon Linke'%>
    </div>

     <div class="actions">
    <%= f.submit "Save" %>
    </div>
<%end%>
</section>
<% flash.each do |type, messages| %>
  <ul class='form-error'>
     <% messages.each do |msg| %>
        <li class="text-center text-red-500"><%= msg %> <i class="fa fa-times"></i></li>
      <% end %>
  </ul>
<% end %> 

app/views/category/show.html.erb
<%= stylesheet_link_tag "category"%> 
<nav class='navbar'>
  <a href="<%= user_category_index_path(current_user.id)%>" > <i class="fa fa-arrow-left"></i></a>
  <p><b>DETAIL</b></p>
  <i></i>
</nav>
<section class='total-amount'>
<h4>Total Amount:</h4>
<h4><%= @total_amount%>$</h4>
</section>
<% if notice%>
 <div id='alert-box'>
  <%= notice%><i class="fa fa-check" aria-hidden="true"></i>
</div>
<%end%>
<section class='detail'>
    <div class='detail-head'>
        <%= image_tag "#{@category.icon}" %>
        <h4><%= @category.name%></h4>
    </div>
    <p>
    lorem ipsum dolor sit amet consectetur adipisicing elit.
     Quisquam, quod. Lorem ipsum dolor sit amet consectetur.
    </p>
    <hr>
   
    <% @transaction_entity.each do |item| %>
      <div class='tranaction'>
      <h4><%= item.name%></h4>
      <p id='amount'><i class='fa fa-money'></i> <%=item.amount%></p><br/>
      <p id='date'><i class='fa fa-calendar'></i> <%= item.created_at.strftime('%B %d %Y')%></p>
    </div>
    <hr>
    <% end %>

</section>

<div id='footer-btn'>
    <div id='btn'>
        <h3><%= link_to 'ADD NEW TRANSACTION' , new_user_category_transaction_path(current_user.id , @category.id)%></h3>
    </div>
</div>

app/views/home/index.html.erb
<section class='welcome-page'>
   <h1 id='app-name'>Easy <br/>Transaction</h1>
    
     <%= link_to 'LOG IN' , new_user_session_path , id: 'login-link'%>

     <%= link_to 'Sign up' , new_user_registration_path , id: 'signup-link'%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='uniq'>

    <%= yield %>

    
  </body>
</html>

app/views/transaction/new.html.erb
<%= stylesheet_link_tag "transaction"%> 
<nav class='navbar'>
  <a href="<%= user_category_index_path(current_user.id)%>" > <i class="fa fa-arrow-left"></i></a>
  <p><b>NEW TRANSACTION</b></p>
  <i class="fa fa-searc"></i>
</nav>  
<section class='category-form'>
<%= form_with model: @transaction_entity , url: user_category_transaction_index_path , method: :post , local: true, class: "form-control" do |f|  %>
    <div class="form-field">
    <%= f.text_field :name , autofocus:  true , autocomplete: "name" , placeholder: 'Enter Transaction Name'%>
    </div>
    <div class="form-field">
       <%= f.number_field :amount , autocomplete: "amount" , placeholder: 'Enter Tranaction Amount'%>
    </div>
    <div class='form-checkbox'>
    <h4>Category:</h4>
    <% @category.each do |category| %>
     <label for="category_id"  class="flex items-center gap-2 flex-nowrap"><%= category.name%></label>
        <%= f.check_box :category_ids , {multiple: true, class: "check-box w-4 h-4 text-primaryDark bg-gray-100 rounded border-gray-300 focus:ring-0 focus:ring-offset-0 dark:border-gray-500"}, category.id, nil %>
      <br/>
      <% end %>
    </div>

     <div class="actions">
    <%= f.submit "ADD" %>
    </div>
<%end%>
</section>

<% flash.each do |type, messages| %>
  <ul class='form-error'>
     <% messages.each do |msg| %>
        <li class="text-center text-red-500"><%= msg %> <i class="fa fa-times"></i></li>
      <% end %>
  </ul>
<% end %> 